### ISSUE TITLE
cnn_breast_mask

### ISSUE THREAD

**Issue by qshwan** [ecalabr/breast_simulated_gad#1]
Hello!
When I run cnn_breast_mask.py ,This error occurs.
ValueError: No parameter files found in model directory breast_simulated_gad-master/breast_mask/checkpoints/
Doesn't this parameter file refer to mask.json? Thank you!

**Comment by ecalabr** [comment]
Looks like you may have figured this out, but I would avoid using the -m argument. If you run the script without -m or -p, then it should automatically find the mask.json param file.

**Comment by qshwan** [comment]
Yes, I get it, thank you! It's really a great project!
